micronaut:
  application:
    name: introspectedJacksonMnIssue

datasources:
  default:
    url: jdbc:h2:mem:entity
    driverClassName: org.h2.Driver
    username: sa
    password: ''

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
